#ifndef TASK_BOARD_PHOTORESISTANCE_PHOTORESISTANCE_H_
#define TASK_BOARD_PHOTORESISTANCE_PHOTORESISTANCE_H_


#include "main.h"


uint8_t Phsis_GetValue(void);


#endif /* TASK_BOARD_PHOTORESISTANCE_PHOTORESISTANCE_H_ */
